# Generated by Django 4.2.30 on 2026-05-06 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Segmento de cliente',
                'verbose_name_plural': 'Segmentos de cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre o razón social')),
                ('codigo_cliente', models.CharField(max_length=64, unique=True, verbose_name='Código interno')),
                ('ciudad', models.CharField(max_length=120)),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('limite_credito', models.PositiveIntegerField(default=0, verbose_name='Límite de crédito (entero, unidades monetarias)')),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='inventario.segmentocliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
