# Generated by Django 4.2.30 on 2026-05-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_datos_iniciales_segmentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='limite_credito',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='segmento',
        ),
        migrations.DeleteModel(
            name='SegmentoCliente',
        ),
    ]
