# Generated by Django 4.2.30 on 2026-05-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_restore_segmento_y_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='limite_credito',
            field=models.PositiveIntegerField(default=0, verbose_name='Límite de crédito (entero, unidades monetarias)'),
        ),
    ]
